export const FORM_TYPES = {
    UPDATE_INPUTS:  'UPDATE_INPUTS',
    SET_INPUT_ERROR: 'SET_INPUT_ERROR',
    SET_LOGIN: 'SET_LOGIN',
    SET_AUTH_TYPE: 'SET_AUTH_TYPE',
    SET_FORM_ERROR_STATUS: 'SET_FORM_ERROR_STATUS'
}

export const APP_TYPES = {
    SET_LOGIN: 'SET_LOGIN',
    SET_MATCHING_JOBS: 'SET_MATCHING_JOBS',
    SET_LOADING_STATE: 'SET_LOADING_STATE'
}